version: '3.9'
services:
  mysql:
    platform: "linux/amd64"
    image: mysql:8.0
    restart: always
    container_name: inventory-management-database
    environment:
      - MYSQL_ROOT_PASSWORD=${PROD_DATABASE_ROOT_PASS}
      - MYSQL_DATABASE=${PROD_DATABASE_NAME}
      - MYSQL_USER=${PROD_DATABASE_USER}
      - MYSQL_PASSWORD=${PROD_DATABASE_PASS}
      - MYSQL_TCP_PORT=${PROD_DATABASE_PORT}
    volumes:
      - db_inventory:/usr/local/mysql/data
    ports:
      - '10000:3307'
    expose:
      - '10000'
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 10s
      retries: 10

  inventory-management-bot:
    platform: "linux/amd64"
    build:
      context: .
      dockerfile: Dockerfile
    image: inventory-management-bot:0.0.5
    container_name: inventory-management-bot
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - MYSQL_ROOT_PASSWORD=${PROD_DATABASE_ROOT_PASS}
      - MYSQL_DATABASE=${PROD_DATABASE_NAME}
      - MYSQL_USER=${PROD_DATABASE_USER}
      - MYSQL_PASSWORD=${PROD_DATABASE_PASS}
      - MYSQL_HOST=${PROD_DATABASE_HOST}
      - MYSQL_PORT=${PROD_DATABASE_PORT}
      - PRODUCTION=true
volumes:
  db_inventory: