STATUS_SUCCESS = 0
STATE_INIT = 1
STATE_WAIT_FOR_CHEESE_TYPE_SELECTION = 2
STATE_WAIT_FOR_COUNT_INPUT = 3
STATE_WAIT_FOR_IS_PACKED_SELECTION = 4
STATE_WAIT_FOR_PACKAGING_SELECTION = 5
STATE_WAIT_FOR_COMMENT_INPUT = 6
