FROM python:3.9-alpine3.17

WORKDIR .

COPY ./demo.py .

CMD ["python", "./demo.py"]



docker push ghcr.io/antiufieiev/inventory-management-bot/test-local-alpine:latest
docker push ghcr.io/antiufieiev/inventory-management-bot:test-local-alpine