version: '3.9'
services:
  mysql:
    platform: "linux/amd64"
    image: mysql:8.0
    restart: unless-stopped
    container_name: inventory-management-database-test
    environment:
      - MYSQL_ROOT_PASSWORD=NotAPass
      - MYSQL_DATABASE=tester
      - MYSQL_USER=management-tester
      - MYSQL_PASSWORD=NotAPass
      - MYSQL_TCP_PORT=3307
    volumes:
      - db_inventory:/usr/local/mysql/data
    ports:
      - '10000:3307'
    expose:
      - '10000'
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 10s
      retries: 10


volumes:
  db_inventory: