name: remote ssh deploy
on: workflow_dispatch

jobs:

    deploy:
        name: docker-compose deploy
        runs-on: ubuntu-latest

        steps:

        - name: checkout
          uses: actions/checkout@v1

        - name: Install SSH Key
          uses: shimataro/ssh-key-action@v2
          with:
            key: ${{ secrets.HOST_PRIVATE_KEY }}
            known_hosts: 'unnecessary'
  
        - name: Adding Known Hosts
          run: ssh-keyscan -p ${{ secrets.HOST_PORT}} -H ${{ secrets.HOST_IP }}  >> ~/.ssh/known_hosts
  
        - name: Adding docker context
          run: |
            docker compose version
            unset DOCKER_HOST
            docker context ls
            docker context create remote1 --docker "host=ssh://${{ secrets.HOST_USERNAME }}@${{ secrets.HOST_IP }}"
            docker context use remote1
            docker context ls

        - name: Log in to registry
          # This is where you will update the personal access token to GITHUB_TOKEN
          run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin

        - name: docker-deploy-test
          env:
            PROD_DATABASE_ROOT_PASS: ${{secrets.PROD_DATABASE_ROOT_PASS}}
            PROD_DATABASE_NAME: ${{secrets.PROD_DATABASE_NAME}}
            PROD_DATABASE_USERs: ${{secrets.PROD_DATABASE_USER}}
            PROD_DATABASE_PASS: ${{secrets.PROD_DATABASE_PASS}}
            PROD_DATABASE_HOST: ${{secrets.PROD_DATABASE_HOST}}
            PROD_DATABASE_PORT: ${{secrets.PROD_DATABASE_PORT}}
            PRODUCTION_TELEGRAM_TOKEN: ${{secrets.DEBUG_TELEGRAM_TOKEN}}
            DEBUG_TELEGRAM_TOKEN: ${{secrets.DEBUG_TELEGRAM_TOKEN}}
            PRODUCTION: false
          run: |
            pwd
            ls -la
            ls -la ./compose-demo/
            cat ./compose-demo/docker-compose.yml
            docker compose -f ./compose-demo/docker-compose-dev.yml up -d --force-recreate --remove-orphans