name: remote ssh deploy
on: workflow_dispatch
env:
  PROD_DATABASE_HOST: "asas"
  PROD_DATABASE_NAME: "asas" 
  PROD_DATABASE_PASS: "asas" 
  PROD_DATABASE_PORT: "asas" 
  PROD_DATABASE_ROOT: "asas" 
  PROD_DATABASE_USER: "asas" 
  PRODUCTION: true
  PRODUCTION_TELEGRAM_TOKEN: "asas" 
  MYSQL_DATABASE: "asasd"

jobs:



    deploy:
        name: git clone and pull
        runs-on: ubuntu-latest
        steps:
        - name: checkout
          uses: actions/checkout@v1
    
        - name: pass envars
          uses: appleboy/ssh-action@v0.1.10
          env:
            HOST_PORT: ${{secrets.HOST_PORT}}
          with:
            host: ${{ secrets.HOST_IP }}
            username: ${{ secrets.HOST_USERNAME }}
            key: ${{ secrets.HOSDT_KEY }}
            port: ${{ secrets.HOST_PORT }}
            envs: HOST_PORT
            script: |
              echo 
              touch test.yml
              ls -la

