name: remote ssh deploy
on: 
  workflow_dispatch:
    inputs:
      PRODUCTION:
        description: 'set PRODUCTION var '
        required: true
        default: 'false'
        type: choice
        options:
          - false
          - true
      HOST_IP:
        description: 'set HOST_IP var '
        required: true
        type: string
      HOST_USERNAME:
        description: 'set HOST_IP var '
        required: true
        default: 'root'
        type: string


jobs:

    deploy:
        name: docker-compose deploy
        runs-on: ubuntu-latest

        steps:

        - name: checkout
          uses: actions/checkout@v1

        - name: Install SSH Key
          uses: shimataro/ssh-key-action@v2
          with:
            key: ${{ secrets.HOST_PRIVATE_KEY }}
            known_hosts: 'unnecessary'
  
        - name: Adding Known Hosts
          run: ssh-keyscan -p ${{ secrets.HOST_PORT}} -H ${{ inputs.HOST_IP }}  >> ~/.ssh/known_hosts
  
        - name: Adding docker context
          run: |
            docker compose version
            docker context ls
            docker context create remote1 --docker "host=ssh://${{ inputs.HOST_USERNAME }}@${{ inputs.HOST_IP }}"
            docker context use remote1
            docker context ls
            docker images ls

        - name: 'Create env file'
          run: |
            echo "${{ secrets.ENV_FILE }}" > ./.env
            echo "DATABASE_PASS:${{ secrets.DATABASE_PASS_TEST }}" >> ./.env
            echo "PRODUCTION:${{ inputs.PRODUCTION }}" >> ./.env
        
        - name: Docker build
          run: |
            docker build -t inventory-management-bot:latest .

        - name: docker-deploy
          run: |
            echo $DOCKER_HOST
            docker ps -a
            cat ./docker-compose.yml
            docker compose -f ./docker-compose.yml up -d --force-recreate --remove-orphans
