name: remote ssh deploy
on: workflow_dispatch

jobs:

    deploy:
        name: docker-compose deploy
        runs-on: ubuntu-latest

        steps:

        - name: checkout
          uses: actions/checkout@v1

        - name: Install SSH Key
          uses: shimataro/ssh-key-action@v2
          with:
            key: ${{ secrets.HOST_PRIVATE_KEY }}
            known_hosts: 'unnecessary'
  
        - name: Adding Known Hosts
          run: ssh-keyscan -p ${{ secrets.HOST_PORT}} -H ${{ secrets.HOST_IP }}  >> ~/.ssh/known_hosts
  
        - name: Adding docker context
          run: |
            docker compose version
            unset DOCKER_HOST
            docker context ls
            docker context create remote1 --docker "host=ssh://${{ secrets.HOST_USERNAME }}@${{ secrets.HOST_IP }}"
            docker context use remote1
            docker context ls

        - name: Log in to registry
          # This is where you will update the personal access token to GITHUB_TOKEN
          run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin

        - name: 'Create env file'
          run: |
            echo "${{ secrets.ENV_FILE }}" > ./compose-demo/.env

        - name: docker-deploy-test
          env: 
            DATABASE_PASS: ${{ secrets.DATABASE_PASS_TEST}}
            MYSQL_ROOT_PASSWORD: ${{secrets.MYSQL_ROOT_PASSWORD}}
            MYSQL_DATABASE: ${{secrets.MYSQL_DATABASE}}
            MYSQL_USER: ${{secrets.MYSQL_USER}}
            MYSQL_PASSWORD: ${{secrets.MYSQL_PASSWORD}}
            MYSQL_TCP_PORT: ${{secrets.MYSQL_TCP_PORT}}
            MYSQL_HOST: 'localhost'
            MYSQL_PORT: ${{secrets.MYSQL_TCP_PORT}}
            PRODUCTION_TELEGRAM_TOKEN: ${{secrets.PRODUCTION_TELEGRAM_TOKEN}}
            DEBUG_TELEGRAM_TOKEN: ${{secrets.DEBUG_TELEGRAM_TOKEN}}

          run: |
            cat ./docker-compose.yml
            docker compose -f ./docker-compose.yml up -d --force-recreate --remove-orphans