name: remote ssh deploy
on: workflow_dispatch

jobs:


    deploy:
        name: git clone and pull
        runs-on: ubuntu-latest
        steps:
        - name: checkout
          uses: actions/checkout@v1
    
        - name: pass envars
          uses: ./
          env:
            HOST_PORT: ${{secrets.HOST_PORT}}
          with:
            host: ${{ secrets.HOST_IP }}
            username: ${{ secrets.HOST_USERNAME }}
            key: ${{ secrets.HOSDT_KEY }}
            port: ${{ secrets.HOST_PORT }}
            envs: HOST_PORT
            script: |
              echo 
              touch test.yml
              ls -la

