name: remote ssh deploy
on: 
  workflow_dispatch:
    inputs:
      PRODUCTION:
        description: 'set PRODUCTION var '
        required: true
        default: 'false'
        type: choice
        options:
          - false
          - true

jobs:

    deploy:
        name: docker-compose deploy
        runs-on: ubuntu-latest

        steps:

        - name: checkout
          uses: actions/checkout@v1

        - name: Install SSH Key
          uses: shimataro/ssh-key-action@v2
          with:
            key: ${{ secrets.HOST_PRIVATE_KEY }}
            known_hosts: 'unnecessary'
  
        - name: Adding Known Hosts
          run: ssh-keyscan -p ${{ secrets.HOST_PORT}} -H ${{ secrets.HOST_IP }}  >> ~/.ssh/known_hosts
  
        - name: Adding docker context
          run: |
            docker compose version
            unset DOCKER_HOST
            export DOCKER_HOST="ssh://root@193.160.119.175"

        - name: 'Create env file'
          run: |
            echo "${{ secrets.ENV_FILE }}" > ./.env
            echo "DATABASE_PASS:${{ secrets.DATABASE_PASS_TEST }}" >> ./.env
            echo "PRODUCTION:${{ inputs.PRODUCTION }}" >> ./.env

        - name: docker-deploy-test
          run: |
            cat ./docker-compose.yml
            docker compose -f ./docker-compose.yml up -d --force-recreate --remove-orphans
