name: remote ssh deploy
on: workflow_dispatch
env:
  PROD_DATABASE_HOST: "asas"
  PROD_DATABASE_NAME: "asas" 
  PROD_DATABASE_PASS: "asas" 
  PROD_DATABASE_PORT: "asas" 
  PROD_DATABASE_ROOT: "asas" 
  PROD_DATABASE_USER: "asas" 
  PRODUCTION: true
  PRODUCTION_TELEGRAM_TOKEN: "asas" 
  MYSQL_DATABASE: "asasd"

jobs:

    deploy:
        name: git clone and pull
        runs-on: ubuntu-latest

        steps:

        - name: checkout
          uses: actions/checkout@v1

        - name: Install SSH Key
          uses: shimataro/ssh-key-action@v2
          with:
            key: ${{ secrets.HOST_PRIVATE_KEY }}
            known_hosts: 'unnecessary'
  
        - name: Adding Known Hosts
          run: ssh-keyscan -p ${{ secrets.HOST_PORT}} -H ${{ secrets.HOST_IP }}  >> ~/.ssh/known_hosts
  
        - name: Adding docker context
          run: |
            docker compose version
            unset DOCKER_HOST
            docker context ls
            docker context create remote1 --docker "host=ssh://${{ secrets.HOST_USERNAME }}@${{ secrets.HOST_IP }}"
            docker context use remote1
            docker context ls

        - name: docker-deploy-test
          run: docker compose -f ./compose-demo/docker-compose.yml up -d 




