name: image_build
on: workflow_dispatch

jobs:

    deploy:
        name: image_build
        runs-on: ubuntu-latest

        steps:

        - name: checkout
          uses: actions/checkout@v1

        - name: Log in to registry
          # This is where you will update the personal access token to GITHUB_TOKEN
          run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin

        - name: Build and push
          uses: docker/build-push-action@v4
          with:
            context: .
            push: true
            tags: inventory-management-bot-prod-slim:v1
